# MiniMessage formatting is supported:
# https://docs.advntr.dev/minimessage/format.html
#
# Placeholders:
#   {player}       The player's username
#   {display_name} The player's display name
#
join:
  # Set enabled to false if you want Paper's default join messages again.
  enabled: true

  message: "<gray>[<green>+<gray>] <yellow>{player}</yellow> joined the server!"

  # If true, this sends no public join message.
  silent: false

  sound:
    enabled: false
    name: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1.0
    pitch: 1.0

  firework:
    enabled: false
    power: 1
    type: BALL
    flicker: false
    trail: true
    colors:
      - LIME
      - YELLOW
    fade-colors:
      - AQUA

leave:
  # Set enabled to false if you want Paper's default leave messages again.
  enabled: true

  message: "<gray>[<red>-<gray>] <yellow>{player}</yellow> left the server."

  # If true, this sends no public leave message.
  silent: false

  sound:
    enabled: false
    name: ENTITY_ITEM_BREAK
    volume: 1.0
    pitch: 1.0
